version: '3'
services:
  pricey_api:
    build: server/
    depends_on:
      - pricey_db
    links:
      - pricey_db
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pricey_db/${POSTGRES_DB}'
      NODE_ENV: staging
  pricey_db:
    build: database/
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
  pricey_ui:
    build: client/
    restart: unless-stopped
    links:
      - pricey_api
    ports:
      - '3000:80'
    environment:
      RUNTIME_API_HOST: 'http://localhost:3000'
